# -*- mode: python ; coding: utf-8 -*-
block_cipher = None
a = Analysis(
    ['print_osmium.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'osmium_chat',
        'osmium_protos',
        'websockets.asyncio.client',
        'mss',
        'mss.tools',
        'PIL',
        'PIL.Image',
        'cryptography.hazmat.primitives.ciphers.aead',
        'Crypto.Cipher.AES',
        'Crypto.Cipher.ChaCha20_Poly1305',
        'win32crypt',
        'tkinter',
        'sqlite3',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Dreadborn',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='dreadborn.ico',
)
